apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-jo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy-jo
  template:
    metadata:
      labels:
        app: haproxy-jo
    spec:
      containers:
      - name: haproxy-jo
        image: bitnami/haproxy:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: haproxy-config-volume-jo
          mountPath: /bitnami/haproxy/conf/haproxy.cfg
          subPath: haproxy.cfg
      volumes:
      - name: haproxy-config-volume-jo
        configMap:
          name: haproxy-config-jo
          items:
              - key: haproxy.cfg
                path: haproxy.cfg


