apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config-jo
data:
  haproxy.cfg: |
    global
        log stdout format raw local0 debug

    defaults
        log global
        mode http
        option httplog
        timeout connect 5s
        timeout client  50s
        timeout server  50s

    frontend http_front
        bind *:8080
        default_backend web_backends

    backend web_backends
        server httpbin2 httpbin.org:80
        server bintang java-openshift-jenkins-abelitang2-dev.apps.rm3.7wse.p1.openshiftapps.com:80 check
        server pandu java-openshift-jenkins-panduass-dev.apps.rm1.0a51.p1.openshiftapps.com:80 check
        server fayad java-openshift-jenkins-rmuhammadfayyadh-dev.apps.rm1.0a51.p1.openshiftapps.com:80 check
        server najah java-openshift-jenkins-sayyidatun-dev.apps.rm1.0a51.p1.openshiftapps.com:80 check
        server hilda java-openshift-jenkins-hildamathilda7-dev.apps.rm1.0a51.p1.openshiftapps.com:80 check


